services:
  neighborville:
    build: .
    container_name: neighborville
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    restart: unless-stopped
    networks:
      - neighborville-net
  
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: neighborville-api
    expose:
      - "3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ALLOWED_ORIGINS=https://domka.me,https://api.domka.me
      - MAILTRAP_HOST=${MAILTRAP_HOST}
      - MAILTRAP_PORT=${MAILTRAP_PORT}
      - MAILTRAP_USER=${MAILTRAP_USER}
      - MAILTRAP_PASS=${MAILTRAP_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
      - MONGO_URI=mongodb://mongo:27017/neighborville
      - REDIS_URI=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    networks:
      - neighborville-net

  mongo:
    image: mongo:latest
    container_name: neighborville-mongo
    expose:
      - "27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=neighborville
    networks:
      - neighborville-net
      
  redis:
    image: redis:alpine
    container_name: neighborville-redis
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - neighborville-net

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 30
    restart: unless-stopped

networks:
  neighborville-net:

volumes:
  mongo-data:
  redis-data: